services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: moto-postgres-dev
    environment:
      POSTGRES_DB: moto_db
      POSTGRES_USER: moto_user
      POSTGRES_PASSWORD: moto_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - moto-network-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U moto_user -d moto_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: moto-rabbitmq-dev
    environment:
      RABBITMQ_DEFAULT_USER: moto_user
      RABBITMQ_DEFAULT_PASS: moto_password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data_dev:/var/lib/rabbitmq
    networks:
      - moto-network-dev
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_dev:
  rabbitmq_data_dev:

networks:
  moto-network-dev:
    driver: bridge
