services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: moto-postgres
    environment:
      POSTGRES_DB: moto_db
      POSTGRES_USER: moto_user
      POSTGRES_PASSWORD: moto_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - moto-network

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: moto-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: moto_user
      RABBITMQ_DEFAULT_PASS: moto_password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - moto-network

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  moto-network:
    driver: bridge
