name: CI/CD Básico - Testes Unitários

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Executar Testes Unitários
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restaurar dependências
      run: dotnet restore moto-backend/moto-backend.sln

    - name: Build da solução
      run: dotnet build moto-backend/moto-backend.sln --no-restore --configuration Release

    - name: Executar Testes Unitários - Domain
      run: dotnet test moto-backend/tests/Moto.Domain.UnitTests/Moto.Domain.UnitTests.csproj --no-build --configuration Release --verbosity normal

    - name: Executar Testes Unitários - Application
      run: dotnet test moto-backend/tests/Moto.Application.UnitTests/Moto.Application.UnitTests.csproj --no-build --configuration Release --verbosity normal